[package]
name = "stellar-registry-name"
version = "0.0.1"
edition = "2024"
description = "Standard name parsing and formatting for Stellar Registry"
license = "Apache-2.0"
repository = "https://github.com/stellar-registry/cli/tree/main/crates/stellar-registry-name"


[lib]
crate-type = ["rlib"]


[dependencies]
thiserror = { workspace = true }
semver = "1.0.28"

[dev-dependencies]
expect-test = "1.5"
